In [2]:
import numpy as np

In [4]:
v = np.array([1,2,3,4,5])
print("A: {}".format(v.shape))
print("B: {}".format(v.dtype))
print("C: {}".format(v.ndim))

A: (5,)
B: int32
C: 1


In [5]:
v = np.arange(15)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
v = np.zeros((2,3,4))
print(v)
v = np.zeros_like(v)
print(v)
v = np.ones((2,3,4))
print(v)
v = np.ones_like(v)
print(v)
v = np.empty((2,3,4))
print(v)
v = np.empty_like(v)
print(v)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [3]:
v = np.array([1,2.3,3,4.4,5.0])
b = v.astype(np.int)
print(v.dtype)
print(b.dtype)
print(b)

float64
int32
[1 2 3 4 5]


In [5]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[3,4,6]])

c = a + b
print(c)

c = a * b
print(c)

c = a - b
print(c)

[[ 8 10 12]
 [ 7  9 12]]
[[ 7 16 27]
 [12 20 36]]
[[-6 -6 -6]
 [ 1  1  0]]


In [6]:
a = 4
b = np.array([[7,8,9],[3,4,6]])

c = a + b
print(c)

c = a * b
print(c)

c = a - b
print(c)

[[11 12 13]
 [ 7  8 10]]
[[28 32 36]
 [12 16 24]]
[[-3 -4 -5]
 [ 1  0 -2]]


In [7]:
a = np.arange(15)
print(a)
a[5:10] = 5
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  5  5  5  5 10 11 12 13 14]


In [52]:
a = np.arange(15)
print(a)
b = a[10:15].copy()
b = 5
print(a)
print(a[::-1])
a = np.arange(4).reshape(2,2)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[[0 1]
 [2 3]]


In [17]:
a2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
print(a2d[:,0]) #arrayof(3)
print(a2d[:,:1]) #arrayof(3,1)

[1 4 7]
[[1]
 [4]
 [7]]


In [25]:
a = np.array(["i","am","awesome"])
a == "i"

array([ True, False, False])

In [26]:
(a =="i") | (a == "am")

array([ True,  True, False])

In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
a = 2
b = np.random.rand(2,2)
print(np.exp(a))
print(np.exp(b))

7.38905609893065
[[1.90647388 1.20674022]
 [1.79390714 1.34995862]]


In [40]:
#meshgrid
x = np.linspace(9,-3,3)
y = np.linspace(11,-4,4)

x_1,y_1 = np.meshgrid(x,y)

In [41]:
#alternativeforifelse

a = [1,2,3,4,5]
b= [-1,-2,-3,-4,-5]
c =[True,False,True,False,True]

np.where(c,a,b)

array([ 1, -2,  3, -4,  5])

In [47]:
a = np.random.rand(3,3)
print(a)
print(np.mean(a))
print(np.std(a))
print(np.sum(a))
print(np.sqrt(a))
print(np.median(a))

[[0.85685212 0.67475937 0.01464661]
 [0.8439167  0.96740096 0.62634839]
 [0.53790503 0.85230153 0.87247311]]
0.6940670905564016
0.2731482121219491
6.246603815007615
[[0.92566307 0.82143738 0.12102317]
 [0.91864939 0.98356543 0.79142175]
 [0.73342009 0.92320178 0.93406269]]
0.8439166998341832


In [53]:
np.eye(3) #idenitymatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])