## Assignment 6

#### Name : Raswanth S.R
#### RollNum : CB.EN.U4CSE19648

#### Exercise 1  Titanic Decision Tree

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

In [32]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [33]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [34]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Data Preprocessing

In [35]:
df.Embarked = df.Embarked.fillna(df['Embarked'].mode()[0])

In [36]:
median_age = df.Age.median()
df.Age.fillna(median_age, inplace = True)

In [37]:
df.drop('Cabin', axis = 1,inplace = True)

In [38]:
df['Fare'].value_counts()

8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
8.4583      1
9.8375      1
8.3625      1
14.1083     1
17.4000     1
Name: Fare, Length: 248, dtype: int64

In [39]:
df['Fare']=df['Fare'].replace(0,df['Fare'].median())

In [40]:
df['GenderClass'] = df.apply(lambda x: 'child' if x['Age'] < 15 else x['Sex'],axis=1)

In [41]:
df[df.Age<15].head(5)

PassengerId  Survived  Pclass                                  Name  \
7             8         0       3        Palsson, Master. Gosta Leonard   
9            10         1       2   Nasser, Mrs. Nicholas (Adele Achem)   
10           11         1       3       Sandstrom, Miss. Marguerite Rut   
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   
16           17         0       3                  Rice, Master. Eugene   

       Sex   Age  SibSp  Parch   Ticket     Fare Embarked GenderClass  
7     male   2.0      3      1   349909  21.0750        S       child  
9   female  14.0      1      0   237736  30.0708        C       child  
10  female   4.0      1      1  PP 9549  16.7000        S       child  
14  female  14.0      0      0   350406   7.8542        S       child  
16    male   2.0      4      1   382652  29.1250        Q       child

In [42]:
df[df.Age>15].head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked GenderClass  
0      0         A/5 21171   7.2500        S        male  
1      0          PC 17599  71.2833        C      female  
2      0  STON/O2. 3101282   7.9250        S      female  
3      0            113803  53.1000        S      female  
4      0            373450   8.0500        S        male

In [43]:
df = pd.get_dummies(df, columns=['GenderClass','Embarked'], drop_first=True)

In [44]:
inputvalues = df.drop(['Name','Ticket','Sex','SibSp','Parch'], axis = 1)
inputvalues.head()

PassengerId  Survived  Pclass   Age     Fare  GenderClass_female  \
0            1         0       3  22.0   7.2500                   0   
1            2         1       1  38.0  71.2833                   1   
2            3         1       3  26.0   7.9250                   1   
3            4         1       1  35.0  53.1000                   1   
4            5         0       3  35.0   8.0500                   0   

   GenderClass_male  Embarked_Q  Embarked_S  
0                 1           0           1  
1                 0           0           0  
2                 0           0           1  
3                 0           0           1  
4                 1           0           1

### Model Building and prediction

In [45]:
X = inputvalues.drop("Survived",axis=1)
X

PassengerId  Pclass   Age     Fare  GenderClass_female  GenderClass_male  \
0              1       3  22.0   7.2500                   0                 1   
1              2       1  38.0  71.2833                   1                 0   
2              3       3  26.0   7.9250                   1                 0   
3              4       1  35.0  53.1000                   1                 0   
4              5       3  35.0   8.0500                   0                 1   
..           ...     ...   ...      ...                 ...               ...   
886          887       2  27.0  13.0000                   0                 1   
887          888       1  19.0  30.0000                   1                 0   
888          889       3  28.0  23.4500                   1                 0   
889          890       1  26.0  30.0000                   0                 1   
890          891       3  32.0   7.7500                   0                 1   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 8 columns]

In [46]:
y = inputvalues.Survived
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [48]:
print(X_train.shape)
print(y_train.shape)

(712, 8)
(712,)


In [49]:
from sklearn import tree
model = tree.DecisionTreeClassifier(criterion = "entropy")
model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [50]:
model.score(X_train, y_train)

1.0

In [51]:
y_pred_train = model.predict(X_train)

In [52]:
y_pred_test = model.predict(X_test)

In [53]:
y_pred_test

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1], dtype=int64)

In [54]:
from sklearn.metrics import confusion_matrix

confusion_matrix = pd.DataFrame(confusion_matrix(y_test, y_pred_test))
print(confusion_matrix)

    0   1
0  90  16
1  25  48


In [55]:
pip install pydotplus

Note: you may need to restart the kernel to use updated packages.


In [56]:
from sklearn.tree import export_graphviz
from io import StringIO
from IPython.display import Image
import pydotplus

In [59]:
dot_data = StringIO()
export_graphviz(model,out_file=dot_data,filled = True,rounded=False,special_characters=True,feature_names=["PassengerId","Pclass","Age","Fare","GenderClass_female","GenderClass_male","Embarked_Q","Embarked_S"])
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

InvocationException: GraphViz's executables not found

In [1]:
# Tried every possibility but can't figure out why the above error isn't solvable

#### Exercise 2  Tumor Decision Tree

### Data Preprocessing

In [4]:
df = pd.read_csv("C:/Users/RASWANTH.SR/Desktop/ML Lab/FDS Lab/csv/data (2).csv")

In [5]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [7]:
df.shape

(569, 33)

In [8]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [9]:
df.dropna(axis=1, inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [12]:
df['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [13]:
df['diagnosis'].replace(['M','B'],[1,0],inplace=True)

In [14]:
df['diagnosis'].value_counts()

0    357
1    212
Name: diagnosis, dtype: int64

### Feature Extraction

In [15]:
df_feature = df.loc[:,["concave points_worst", "perimeter_worst", "concave points_mean", "radius_worst", "perimeter_mean", "area_worst", "radius_mean", "area_mean" ,"concavity_mean", "concavity_worst"]]
df_feature.describe()

concave points_worst  perimeter_worst  concave points_mean  \
count            569.000000       569.000000           569.000000   
mean               0.114606       107.261213             0.048919   
std                0.065732        33.602542             0.038803   
min                0.000000        50.410000             0.000000   
25%                0.064930        84.110000             0.020310   
50%                0.099930        97.660000             0.033500   
75%                0.161400       125.400000             0.074000   
max                0.291000       251.200000             0.201200   

       radius_worst  perimeter_mean   area_worst  radius_mean    area_mean  \
count    569.000000      569.000000   569.000000   569.000000   569.000000   
mean      16.269190       91.969033   880.583128    14.127292   654.889104   
std        4.833242       24.298981   569.356993     3.524049   351.914129   
min        7.930000       43.790000   185.200000     6.981000   143.500000   
25%       13.010000       75.170000   515.300000    11.700000   420.300000   
50%       14.970000       86.240000   686.500000    13.370000   551.100000   
75%       18.790000      104.100000  1084.000000    15.780000   782.700000   
max       36.040000      188.500000  4254.000000    28.110000  2501.000000   

       concavity_mean  concavity_worst  
count      569.000000       569.000000  
mean         0.088799         0.272188  
std          0.079720         0.208624  
min          0.000000         0.000000  
25%          0.029560         0.114500  
50%          0.061540         0.226700  
75%          0.130700         0.382900  
max          0.426800         1.252000

### Model Building and Prediction

In [16]:
y = df.iloc[:,1]
X = df.loc[:,["concave points_worst", "perimeter_worst", "concave points_mean", "radius_worst", "perimeter_mean", "area_worst", "radius_mean", "area_mean" ,"concavity_mean", "concavity_worst"]]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [18]:
print(X_train.shape)
print(y_train.shape)

(455, 10)
(455,)


In [19]:
from sklearn import tree
model = tree.DecisionTreeClassifier(criterion = "entropy")
model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [20]:
model.score(X_train, y_train)

1.0

In [21]:
y_pred_train = model.predict(X_train)

In [22]:
y_pred_test = model.predict(X_test)

In [23]:
y_pred_train

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,

In [24]:
y_pred_test

array([1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0], dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix

confusion_matrix = pd.DataFrame(confusion_matrix(y_test, y_pred_test))
print(confusion_matrix)

    0   1
0  71   1
1   6  36


In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_test)

0.9385964912280702

### Salary Decision Tree

In [28]:
df = pd.read_csv("C:/Users/RASWANTH.SR/Desktop/ML Lab/FDS Lab/csv/salaries (2).csv")

In [29]:
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [30]:
inputs = df.drop('salary_more_then_100k',axis=1)

In [31]:
target = df["salary_more_then_100k"]

In [33]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
inputs['company_n'] = label_encoder.fit_transform(inputs['company'])
inputs['job_n'] = label_encoder.fit_transform(inputs['job'])
inputs['degree_n'] = label_encoder.fit_transform(inputs['degree'])
inputs.sample(5)

company               job     degree  company_n  job_n  degree_n
8   abc pharma  business manager  bachelors          0      0         0
3       google  business manager    masters          2      0         1
13    facebook  business manager    masters          1      0         1
11    facebook   sales executive    masters          1      2         1
0       google   sales executive  bachelors          2      2         0

In [35]:
inputs.drop(['company','job','degree'],inplace=True,axis=1)

In [36]:
inputs

company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [37]:
from sklearn import tree
model = tree.DecisionTreeClassifier(criterion = "entropy")
model.fit(inputs, target)

DecisionTreeClassifier(criterion='entropy')

In [39]:
model.score(inputs, target)

1.0

In [42]:
model.predict([[2,1,0]])

array([0], dtype=int64)

In [43]:
model.predict([[2,1,1]])

array([1], dtype=int64)

In [44]:
model.predict([[2,0,1]])

array([1], dtype=int64)